### ISSUE TITLE
bar:command not found frankenwm:other wm is running 

### ISSUE THREAD

**Issue by GithubAccount453** [sulami/FrankenWM#102]
https://gist.github.com/sulami/d6a53179d6d7479e0709

**Comment by sulami** [comment]
Hey, can you be more precise in what you're actually observing?

**Comment by GithubAccount453** [comment]
Hi thanks so much for the response! When I run frankenwm2bar.sh script I get the following output: frankenwm2bar.sh: line 27: bar: command not found frankenwm error: other wm is running : No child processes

**Comment by sulami** [comment]
Happy new year, sorry for the delay.

The message above hints at several things:

- it can't find the executable for `bar` in your `$PATH`
- another window manager is already running and bound to X, blocking FrankenWM from acquiring control over the windows
