### ISSUE TITLE
Just a short question

### ISSUE THREAD

**Issue by voidpin** [sulami/FrankenWM#107]
Hi,
So, I've packaged and now maintain `frankenwm` on NetBSD.
I was using `spectrwm` prior to this but, I'm now running the git-master branch of `frankenwm` on my machine.
Very happy with it :)
To the question, is there a way to make the WM use some cursor-theme? When inside Gtk or Qt apps is fine but, when no window exists it uses the big X from x11. I'm getting used to it but still wonder... `spectrwm` didn't do this.
Note, I never specify any cursor-theme to use on either WM's.

Again, just asking. Its no big issue. Thanks for this WM.

**Comment by sulami** [comment]
pin <notifications@github.com> writes:

> Hi,
> So, I've packaged and now maintain `frankenwm` on NetBSD.
> I was using `spectrwm` prior to this but, I'm now running the git-master branch of `frankenwm` on my machine.
> Very happy with it :)
> To the question, is there a way to make the WM use some cursor-theme? When inside Gtk or Qt apps is fine but, when no window exists it uses the big X from x11. I'm getting used to it but still wonder... `spectrwm` didn't do this.
> Note, I never specify any cursor-theme to use on either WM's.
>
> Again, just asking. Its no big issue. Thanks for this WM.

I think this is probably related to the root window and its properties.
I don't know off the bat what exactly to change without looking at ABI
docs, but I'd guess that that should be possible to set to inherit from
somewhere or other.

-- 
Robin

**Comment by voidpin** [comment]
Thanks!
As mentioned, there's no big deal :)
