### ISSUE TITLE
Just another quick question

### ISSUE THREAD

**Issue by voidpin** [sulami/FrankenWM#109]
@sulami 
I've been using `frankenwm` since the work on packaging it for NetBSD.
I'm very happy with it and looking no further. Great WM!

Do you have any experience integrating it on a DE?
Anything to think about if I was to replace `openbox` by `frankenwm` on LXQt?
Any config in `config.h` I should be careful about?

Thanks!

Please feel free to close the issue.

**Comment by sulami** [comment]
> Do you have any experience integrating it on a DE?
> Anything to think about if I was to replace openbox by frankenwm on LXQt?

I haven't actually tried that, but that should't be too bad in theory, given that it can leave space for a panel either on top or bottom. I'd just give it a go, I don't see any obvious reason why it wouldn't work. Let me know if it needs any adjustments for that.

> Any config in config.h I should be careful about?

Apparently `FOLLOW_MOUSE` can be a bit dodgy at times, c.f. #108, but you already know about that.

**Comment by voidpin** [comment]
Thanks, I'll give it a try and let you know how it goes.
If it works, I wounder what to call it 🙄
`cutefranken` perhaps 😁

**Comment by voidpin** [comment]
@sulami it worked fine, despite a few glitches. Had to stop the loading of the default config keys, as I was expecting.
But, also had to give away the desktop control to `frankenwm` for it to work.

I guess, I could invest some more time on this and make it work better but, I think I'll just go back to use only the window manager.

![2020-11-19-115431_1366x768_scrot](https://user-images.githubusercontent.com/35956139/99658184-6cc45d00-2a5f-11eb-86bd-9d44bb8b8b15.png)

Closing this issue now :)
