### ISSUE TITLE
frankenwm2bar.sh - frankenwm: error: other wm is running : No child processes

### ISSUE THREAD

**Issue by KriegNL** [sulami/FrankenWM#110]
There was a thread about this issue before but a solution was no provided by OP.
I've been googling and searching but i can't seem to figure this out.

I changed _bar_ to _lemonbar_ in the script. 

Launching frankenwm2bar.sh from a terminal results in:

```
frankenwm: error: other wm is running
: No child processes
```

My .xinitrc:

```
#!/bin/sh
exec frankenwm & wmpid=$!
sleep 2
~/.config/scripts/bar.sh &
~/.config/scripts/display.sh external &
hsetroot -cover ~/Pictures/Wallpapers/Wal_1.jpg &
xrdb -load /home/rico/.Xresources &
wait $wmpid
```
Lemonbar launches and shows me the date and time but nothing else.

I'm not sure what is causing this or what i should google for. Any help is greatly appeciated.

EDIT:
Distro: Arch
FrankenWM built from source.

EDIT:
Error message might be unrelated to my problem.
frankenwm.fifo seems to be empty.
As suggested in a different threed i set EWHM_TASKBAR to False, didn't work tho.

**Comment by sulami** [comment]
Just to make sure:

Are you launching FrankenWM from your `.xinitrc`, and then try to run `frankenwm2bar.sh`? If so, the solution is simple: `frankenwm2bar.sh` is launching FrankenWM (again), because it doesn't actually write to the FIFO, it just writes to stdout. So just use the script in your `.xinitrc` and it will load up FrankenWM and redirect the output into the FIFO, where your bar can read it from.

**Comment by KriegNL** [comment]
Thank you so much for your reply!
I was launching the bar script _after_ launching frankenwm via .xinitrc.

I replaced _exec frankenwm_ in my .xinitrc with the bar script.
Frankenwm and lemonbar both start but, aside from the clock, i don't get anything else.

Added a screenshot of my .xinitrc, the bar script and the bar as i get i on launch.
![bar](https://user-images.githubusercontent.com/68593093/100620080-48e5fe80-331e-11eb-84ae-d107a30fd47d.png)

I just might have enough info to go figure it out myself, if you could provide me with aditional info it would be highly appreciated.

**Comment by sulami** [comment]
I haven't used lemonbar myself, so I'm not sure if the format the script
generates works out for that.

I don't have any concrete tips, but I'd try not starting lemonbar,
grabbing some of the data from the FIFO and manually passing that into
lemonbar. If that doesn't work out then it's a formatting issue and you
can play with the format until the bar shows something, and then adapt
the script to generate the correct format.

That script is a serious mess that I haven't looked at in over half a
decade, so I'd try to do any debugging away from that if you can.

Good luck!

**Comment by KriegNL** [comment]
I kinda figured that Lemonbar would be an drop-in replacement for Bar, probably not.

My problems were not bug related but just me not understanding how the script worked.
I've got enough info to start working on something myself, thank you so much for the helpful replies!
I'll mark this thread solved.

Big thank you for your work on FrankenWM, it's an amazing window manager and i love using it.
