### ISSUE TITLE
How to autostart application on login ?

### ISSUE THREAD

**Issue by RohitSingh107** [sulami/FrankenWM#111]
Hello, I am really impressed with window manager, no doubt it's one of the best. I am used the autostart application using autostart.sh script but I can't find the way to do this here. But how to autostart applications ?

**Comment by sulami** [comment]
Thanks for the kind words.

Autostarting depends on the surrounding environment. You could run the
WM from ~/.xinitrc, which is a common way. See
https://wiki.archlinux.org/index.php/Xinit for more information on that.

If you are using a display manager, you can also use that, which is
probably easier. More information on that here:
https://wiki.archlinux.org/index.php/Display_manager

**Comment by RohitSingh107** [comment]
Thanks it worked and congratulation for this fantastic WM.
