### ISSUE TITLE
Unable to set top bar/panel using polybar.

### ISSUE THREAD

**Issue by RohitSingh107** [sulami/FrankenWM#112]
Unable to set top bar/panel using polybar. Bottom bar works perfectly but top bar don't work.

Here is what I do and what I get
$ polybar mybar -c path/to/my/bar
Output:> Segmentation fault (core dumped))

top bar works in other window managers but not work in frankenwm.

**Comment by sulami** [comment]
I haven't heard of that one. I'd suggest asking the folks over at
polybar for suggestions, as I don't even know where I'd start debugging
this.

**Comment by RohitSingh107** [comment]
it sometimes work and most of time don't work, btw Thanks. I will investigate more about it.
