### ISSUE TITLE
Autostarting picom and polybar when launching Frankenwm

### ISSUE THREAD

**Issue by petrolblue** [sulami/FrankenWM#115]
Hi,
so I've just installed FrankenWM and love it so far, very fast and minimal window manager, but is there any way to autostart applications or daemons like picom, polybar, emacsclient etc. in FrankenWM with a shell script or in the config itself? Im not very experienced in C so I don't know if this is a stupid question.

Thanks a million in advance

**Comment by sulami** [comment]
David Burns ***@***.***> writes:

> Hi,
> so I've just installed FrankenWM and love it so far, very fast and
> minimal window manager, but is there any way to autostart applications
> or daemons like picom, polybar, emacsclient etc. in FrankenWM with a
> shell script or in the config itself? Im not very experienced in C so
> I don't know if this is a stupid question.
>
> Thanks a million in advance

Hey,

There's currently no builtin way of launching additional applications,
though this is a design decision and not a technical limitation. If you
wanted to it would be trivial to hack into in, see man 3 exec.

What you probably want to do is start any additional applications via
either your ~/.profile or using some other kind of launch agent, eg.
using a systemd service[0], depending on your system and application.

This also prevents crashing/restarting the window manager from killing
all child processes.

[0]: https://wiki.archlinux.org/title/Systemd#Writing_unit_files

-- 
Robin

**Comment by petrolblue** [comment]
Hi,

thanks for the response, it worked. I didn't know this was an option as well.
