### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by Ypnose** [sulami/FrankenWM#29]
Hi,
Please add release(s) for maintainers.

**Comment by sulami** [comment]
Done.

**Comment by Ypnose** [comment]
Cool. Try to do the same thing when you judge it's the right time. Maintainers will be able to package it easily.

**Comment by sulami** [comment]
On Wed, Jun 17, 2015 at 10:14:21AM -0700, Ypnose wrote:
> Cool. Try to do the same thing when you judge it's the right time.
> Maintainers will be able to package it easily.
> 
I will. Btw, thanks for packaging FrankenWM, appreciate it.

-- 

Robin Schroer
