### ISSUE TITLE
Dunst notification

### ISSUE THREAD

**Issue by lucafav** [sulami/FrankenWM#31]
If i change workspace, notifications are hidden by open windows.

**Comment by sulami** [comment]
On Sun, Jun 28, 2015 at 02:52:07PM -0700, lucafavario wrote:
> If i change workspace notification is hidden by open windows. 
> 
Hm, we could probably fix this by raising notification windows after a
workspace switch. I'll see what I can do.

-- 

Robin Schroer

**Comment by lucafavario** [comment]
Than

**Comment by sulami** [comment]
Please try out the `31-fix` branch that I just pushed. I have no means
to easily produce notification windows here, so you will have to tell me
if this works. If so, I will merge it into master.

-- 

Robin Schroer

**Comment by lucafavario** [comment]
I've tried it and doesn't work if the window which hides the notification is focused or there are less than 3 windows open. Otherwise with some layouts it works, but with others it doesn't. I can't understand the exact conditions when it works or does not...

**Comment by sulami** [comment]
On Tue, Jun 30, 2015 at 10:15:28AM -0700, lucafavario wrote:
> I've tried it and doesn't work if the window which hides the
> notification is focused or there are less than 3 windows open.
> Otherwise with some layouts it works, but with others it doesn't. I
> can't understand the exact conditions when it works or does not...

Very interesting...

As I am basically just trying things out here, I pushed another attempt,
maybe this will help. But in terms of the logic, all EWMH notification
windows should get raised after the remapping and retiling of the
windows is done.

-- 

Robin Schroer

**Comment by lucafavario** [comment]
Same as before. I understand the logic but i can't help with the code...

**Comment by sulami** [comment]
On Tue, Jun 30, 2015 at 10:30:12AM -0700, lucafavario wrote:
> Same as before. I understand the logic but i can't help with the code... 
> 
This is very interesting, especially the fact that it seems to work
sometimes but not all the time. May I ask what kind of notification
window we are talking about? At this point, I cannot really explain, how
anything but the scratchpad window could cover a proper EWMH
notification after a workspace switch.

Nontheless, have another commit.

-- 

Robin Schroer

**Comment by lucafavario** [comment]
I'm using <a href="https://packages.debian.org/sid/dunst"> dunst notification daemon </a> on debian. I use it with notify-send and programs use it when they notification. 
The commit wan't successfull.

**Comment by sulami** [comment]
On Wed, Jul 01, 2015 at 07:52:55AM -0700, lucafavario wrote:
> I'm using <a href="https://packages.debian.org/sid/dunst"> dunst notification daemon </a> on debian. I use it with notify-send and programs use it when they notification. 
> The commit wan't successfull. 
> 
Okay, I installed Dunst and played a little bit with it. While it
properly sets up the EWMH window type and everything, it does get
ignored in FrankenWM's internal client list, because it maps itself as
opposed to request mapping from the window manager. Self-mapping windows
are currently not supported at all by FrankenWM, meaning they just get
ignored, and as such overdrawn as soon as another client gets mapped in
the same spot.

Adding support for self-mapping windows would be quite a task, so if I
should do this, it might take quite a while until it is done.

-- 

Robin Schroer

**Comment by lucafavario** [comment]
Ok i understand! It's not a big problem, don't waste time only to make notifications work!

**Comment by t4nkw4rt** [comment]
working on that enhancement. maybe I've found a simple way to implement it.

**Comment by t4nkw4rt** [comment]
First catch _NET_WM_WINDOW_TYPE_NOTIFICATION windows in mapnotify();
then raise them in update_current();
works well with dunst.

https://github.com/t4nkw4rt/FrankenWM/tree/iss31

**Comment by sulami** [comment]
Should have been fixed by @t4nkw4rt (thanks for that!). Reopen otherwise.
