### ISSUE TITLE
Border missing from first window 

### ISSUE THREAD

**Issue by Houseoftea** [sulami/FrankenWM#37]
Just something I noticed but whenever I start an x session and open my first window It does not have a border around it.

When I open a second window borders will appear around both of them.

Any idea whats going on? thanks.

**Comment by sulami** [comment]
On Mon, Jul 20, 2015 at 06:14:15AM -0700, Houseoftea wrote:
> Just something I noticed but whenever I start an x session and open my
> first window It does not have a border around it.
> 
> When I open a second window borders will appear around both of them.
> 
> Any idea whats going on? thanks.
> 
Hm, not really. Does it happen regardless which window you open? Which
layout are you in at that point? Does it only happen once after startup?

-- 

Robin Schroer

**Comment by Houseoftea** [comment]
Ohhh Im an idiot! 
Its actually just the borders on monocle mode setting.
By default the first window will not have borders because it is considered monocle mode.

**Comment by sulami** [comment]
On Wed, Jul 22, 2015 at 07:29:49AM -0700, Houseoftea wrote:
> Ohhh Im an idiot! 
> Its actually just the borders on monocle mode setting.
> By default the first window will not have borders because it is
> considered monocle mode. 
> 
Happens to the best, glad you figured it out. Have fun using FrankenWM
and don't hesitate reporting possible bugs.

-- 

Robin Schroer
