### ISSUE TITLE
Compile issues

### ISSUE THREAD

**Issue by Houseoftea** [sulami/FrankenWM#38]
This didn't happen before, I poked around for a solution.
I have a feeling its another one of those obvious things that Ive missed

![2015-07-28-213813_562x397_scrot](https://cloud.githubusercontent.com/assets/13292966/8944595/1d0a521c-3571-11e5-9ead-e4cbe7d9f7d5.png)

**Comment by Houseoftea** [comment]
Nevermind again! I just needed pkg-config

**Comment by sulami** [comment]
By the way, I'm noticing you seem to be using Void Linux. Ypnose maintains an official FrankenWM Void package (shoutout to him!).

**Comment by Houseoftea** [comment]
My computers name is void ;) 
But I have been thinking about switching to it.
The official package just sweetens the pot
