### ISSUE TITLE
Reload on the fly

### ISSUE THREAD

**Issue by renodesper** [sulami/FrankenWM#39]
Is there any plan to add reload functionality? Kind of compile and reload in Xmonad. It's a bit long if I have to do it manually, so it will be a great to have this functionality without closing X. Thank you.

**Comment by sulami** [comment]
That might be possible, yes. On the other hand, may I ask which setting in particular you would want to be able to change on the fly?

**Comment by renodesper** [comment]
What I mostly edit right now is application's rule, command, and shortcut. Application's rule is a bit more important for me since I should check one by one whether the title is right or not (I try to put "Pidgin" in workspace 3 but I guess the title is not "Pidgin").

**Comment by kazcw** [comment]
@renodesper I use something like this in my .xinitrc:
`while true; sleep 1; done`
Then you can just exit frankenwm to reload it; you'll lose all layout state, but it's much easier to rearrange your windows than to recreate a whole X session, and doesn't require complicated state persistence code in the wm :)

**Comment by renodesper** [comment]
@kazcw I already did that, but everytime I kill it (frankenwm), the first workspace is full of many black window applications. When I investigated it with xprop, those windows is my daemon applications. Here is the picture:
![2015-09-18-185439_1366x768_scrot](https://cloud.githubusercontent.com/assets/807413/9958796/8a5b3e0a-5e37-11e5-8727-8adf09ea024e.png)

This is my autostart.sh and frankenwm.sh:
- https://gist.github.com/renodesper/f18e51816b72721e07f3
- https://gist.github.com/renodesper/5a20b645c421c16d25c8

I use it like this in my .xinitrc:
```
~/.autostart.sh &
exec ~/.scripts/frankenwm.sh
```

**Comment by kazcw** [comment]
Yeah, I've noticed the same issue. I've opened #42 with a description. I have a patch I've been using, I'll get a PR together.

**Comment by renodesper** [comment]
@kazcw great, those black window doesn't appear anymore, I guess we can close this issue.
