### ISSUE TITLE
Tabbed layout

### ISSUE THREAD

**Issue by renodesper** [sulami/FrankenWM#40]
Can we add tabbed layout into frankenwm? It will be like monocle layout but we will know all windows that we have in the workspace by looking into the tab.

**Comment by kazcw** [comment]
If we supported the WM_DESKTOP EWMH property, an simple external tool could use EWMH to listen for title changes on a particular desktop and write the output to a dzen bar or something. When the bar's clicked it would trigger xdotool or an EWMH call to focus the specified window.

**Comment by renodesper** [comment]
@kazcw is there any workaround to get WM_DESKTOP manually to use with dzen2?
