### ISSUE TITLE
FIFO

### ISSUE THREAD

**Issue by TaylanTatli** [sulami/FrankenWM#52]
Hi. I'm trying your wm and so far so good. There is one problem, I'm using lightdm to start frankenwm. So couldn't figure out how to create fifo for panel. I changed xsession file's exec line, like this: frankenwm > /tmp/frankenwm.fifo but it didn't login. What can i do to use panel? Sorry for noob question. Thanks.

**Comment by sulami** [comment]
I have some sample scripts that showcase how to connect a bar and parse
the output in which you are probably interested:

https://gist.github.com/sulami/d6a53179d6d7479e0709

-- 

Robin Schroer

**Comment by TaylanTatli** [comment]
Thank for quick reply. 
But they don't work after login. So I have to start frankenwm with a script to use panel. But this is not what i want. I want to start frankenwm and after that start panel. I don't want to logout and login to make som changes on panel.

**Comment by TaylanTatli** [comment]
I found this: https://gitlab.com/aesdana/anadsea/blob/master/bin/minimalenv/panel  
It seems using xprop will solve my problem.  
Thank you.
