### ISSUE TITLE
FOLLOW_MOUSE does not seem to work

### ISSUE THREAD

**Issue by Vortelf** [sulami/FrankenWM#93]
What I have in my config is this:

`
# define ATTACH_ASIDE        True
# define FOLLOW_MOUSE      True
# define FOLLOW_WINDOW   True
# define CLICK_TO_FOCUS    False

`
But it's not working and I don't know where I've gone wrong configuring it. I'd be glad if someone point me where's my mistake.

Beside that, I'm struggling with the autostart. I'd appreciate this too :)

Have a nice day.

**Comment by Laundry-96** [comment]
I have this same problem too! I have thought it was just me... I'll see if I can take a look at the previous commits and see a difference.

**Comment by Laundry-96** [comment]
If you go back to commit 545a695 to get it working again (This isn't the last commit where it was working, it just happens that I picked this one to go to, and it was working)

**Comment by Laundry-96** [comment]
I have narrowed down the two commits that the change happened in. They are 7ccb69b and 13c1289. A lot of code was changed here, and I'm not familiar with this project, so I'll leave it to the developers.

**Comment by ciscon** [comment]
bump?

**Comment by sulami** [comment]
I fixed this, at least it works for me (though I don't usually use it). If you check out the commit you can spot easily why it wasn't working. I also bumped the AUR version, if you're using that.
