### ISSUE TITLE
No Output to Statusbar?

### ISSUE THREAD

**Issue by ode79** [sulami/FrankenWM#96]
I have been trying to setup a status bar in FrankenWM.

I copied the dzen2 scripts from your gist.

When I run then as written they both fail to start with errors:

frankenwm2dzen-dwmlike.sh:
```
~/bin/frankenwm2dzen-dwmlike.sh: 6: ~/bin/frankenwm2dzen-dwmlike.sh: Syntax error: "(" unexpected
```
frankenwm2dzen.sh
```
~/bin/frankenwm2dzen.sh: 6: ~/bin/frankenwm2dzen.sh: [[: not found
~/bin/frankenwm2dzen.sh: 10: ~/bin/frankenwm2dzen.sh: Syntax error: "(" unexpected (expecting "done")
```
I changed the sh to bash in the shebangs and ran them again.
Now they start but I just get the a blank status bar at the top of the screen, and the I cannot quit the window manager when running the dwmlike version of the script.

I deleted the pipe in the tmp dir between attempts.

I also tried changing the shell to zsh in the shebang but the results were the same as bash.

**Comment by extrasharp** [comment]
i was having a similar issue not seeing any desktopinfo when tesing my config with Xephyr.
i solved it by commenting out the line '#define EWMH_TASKBAR True' in the default config.h and rebuilding. now i am getting proper output to process for a bar~

**Comment by ode79** [comment]
Thanks, this fixed the issue for me.
